name: Setup stddoc documentation generator
description: Installs the stddoc documentation manager into the runner

runs:
  using: "composite"
  steps:

    - if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir -p "${GITHUB_ACTION_PATH}/bin"
        make -j -C "${GITHUB_ACTION_PATH}" "BIN=bin/stddoc"
        echo "${GITHUB_ACTION_PATH}/bin" >> $GITHUB_PATH

    - if: runner.os == 'Windows'
      shell: bash
      run: |
        mkdir -p "${GITHUB_ACTION_PATH}/bin"
        make -j -C "${GITHUB_ACTION_PATH}" "BIN=bin/stddoc.exe" "CC=/c/msys64/mingw64/bin/clang"
        echo "${GITHUB_ACTION_PATH}/bin" >> $GITHUB_PATH
