name: Setup stddoc documentation generator
description: Installs the stddoc documentation manager into the runner

runs:
  using: "composite"
  steps:

    - if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir -p "${GITHUB_ACTION_PATH}/bin"
        make -j -C "${GITHUB_ACTION_PATH}" "BIN=bin/stddoc"
        echo "${GITHUB_ACTION_PATH}/bin" >> $GITHUB_PATH

    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item "${GITHUB_ACTION_PATH}/bin" -ItemType Directory -ea 0
        make -j -C "${GITHUB_ACTION_PATH}" "BIN=bin/stddoc.exe"
        Join-Path $env:GITHUB_ACTION_PATH "bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
