---

name: Compile Release
on:
  push:
    tags:
      - '*'

jobs:

  build-windows:
    name: Build and upload artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            cc: clang
            bin: stddoc-win-x64.exe
    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |
          echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH

      # - uses: finwo/dep@main
      #   name: Install dep

      # - name: Install dependencies
      #   run: dep install
      #   shell: bash

      - name: Build
        run: make -j CC=${{ matrix.cc }} BIN=${{ matrix.bin }}
        shell: bash

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bin }}
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}

  build-linux:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - distro: ubuntu_latest
            arch: aarch64
            cc: gcc
            bin: stddoc-lin-aarch64

          - distro: ubuntu_latest
            arch: armv7
            cc: gcc
            bin: stddoc-lin-armv7

          - distro: ubuntu_latest
            arch: riscv64
            cc: gcc
            bin: stddoc-lin-riscv64

          - distro: ubuntu_latest
            arch: none
            cc: gcc
            bin: stddoc-lin-x64

    steps:

      - uses: actions/checkout@v3

      # - uses: finwo/dep@main
      #   name: Install dep

      # - name: Install dependencies
      #   shell: bash
      #   run: dep install

      - if: ${{ matrix.arch != 'none' }}
        uses: uraimo/run-on-arch-action@v2
        name: Build
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}

          install: |
            apt-get update -y
            apt-get install -yq build-essential libglib2.0-dev

          run: |
            make -j CC=${{ matrix.cc }} BIN=${{ matrix.bin }}

      - if: ${{ matrix.arch == 'none' }}
        name: Build
        shell: bash
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq build-essential libglib2.0-dev
          make -j CC=${{ matrix.cc }} BIN=${{ matrix.bin }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bin }}
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
